spring:
  application:
    name: spCloud
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/spCloudDb?serverTimezone=GMT%2B8"
    username: root
    password: 11111111